name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  crates_io_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Publish to Crates.io
        run: cargo publish --token ${{secrets.CRATES_IO_API_KEY}}